services:
    open-meteo:
        image: ghcr.io/open-meteo/open-meteo
        container_name: open-meteo
        restart: unless-stopped
        ports:
            - '127.0.0.1:8080:8080'
        volumes:
            - open-meteo-data:/app/data
        environment:
            - REMOTE_DATA_DIRECTORY=https://openmeteo.s3.amazonaws.com/data/
            - CACHE_SIZE=8GB

volumes:
    open-meteo-data:
